# Tensor 编程练习

请尝试使用学到的tensor知识，完成下述问题。

In [18]:
import torch
import cv2
img = cv2.imread('template.jpg')
import numpy as np

### 1. tensor的创建、属性修改、索引、拼接、维度调整等

（1）使用opencv读取的图像默认是BGR三通道的ndarrays格式，数据类型是uint8。基于pytorch实现的神经网络往往要求输入数据使用float32类型，请创建一个和img具有相同内容的tensor，并将其数据类型调整为float32。

In [15]:
x = torch.tensor(img, dtype=torch.float32, device='cpu')

（2）请取出该tensor表示的图像的上半部分，即对于尺寸为（48，48，3）的图像取出前24行得到尺寸为（24，48，3）的tensor，命名为img_top。类似地，请再取出图像的下半部分，得到另一个尺寸为（24，48，3）的tensor，命名为img_down。

In [7]:
img_top=x[0:24,0:48,0:3]
img_down=x[24:48,0:48,0:3]
print(img_top)
print(img_down)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0.

（3）请将img_down置于img_top上方对二者进行拼接，得到尺寸为（48，48，3）的tensor，命名为img_cat。


In [30]:
img_cat = torch.cat([img_down, img_top], dim=0)

（4）在pytorch实现的神经网络中，往往要求输入图像具有(batch_size, channel, height, width)的维度顺序。请将拼接后的img_cat从(height, width, channel)的维度顺序调整为(batch_size, channel, height, width)的顺序，命名为img_pytorch, 其中batch_size应为1。

In [31]:
img_unsqueeze = img_cat.unsqueeze(-1)
img_pytorch=img_unsqueeze.permute(3, 2, 0, 1)
print(img_pytorch.shape)

torch.Size([1, 3, 48, 48])


### 2. tensor的数学运算

（1）提供的模板图像是一幅黑白图像，可以很容易地根据三通道值之和是否为0来区分背景和前景。请据此得到img_pytorch的前景mask，命名为img_mask，img_mask应具有(batch_size, height, width)的维度，并且数据类型应为float32。

In [37]:
img_mask=torch.zeros(1,48,48,dtype=torch.float32,device='cpu')
for i in range(48):
    for j in  range(48):
        count=0
        for k in range(3): 
            count+=img_pytorch[0,k,i,j]
        if(count!=0):
            img_mask[0,i,j]=count
print(img_mask)



tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


（2）请对img_pytorch的前景部分添加在[-50, 0]之间均匀分布的随机噪声，结果命名为img_noise，可以使用前面获得的前景mask。

In [39]:
import random
number = random.uniform(-50,0)
img_noise=img_pytorch+number
print(img_noise)

tensor([[[[-27.2691, -27.2691, -27.2691,  ..., -27.2691, -27.2691, -27.2691],
          [-27.2691, -27.2691, -27.2691,  ..., -27.2691, -27.2691, -27.2691],
          [-27.2691, -27.2691, -27.2691,  ..., -27.2691, -27.2691, -27.2691],
          ...,
          [-27.2691, -27.2691, -27.2691,  ..., -27.2691, -27.2691, -27.2691],
          [-27.2691, -27.2691, -27.2691,  ..., -27.2691, -27.2691, -27.2691],
          [-27.2691, -27.2691, -27.2691,  ..., -27.2691, -27.2691, -27.2691]],

         [[-27.2691, -27.2691, -27.2691,  ..., -27.2691, -27.2691, -27.2691],
          [-27.2691, -27.2691, -27.2691,  ..., -27.2691, -27.2691, -27.2691],
          [-27.2691, -27.2691, -27.2691,  ..., -27.2691, -27.2691, -27.2691],
          ...,
          [-27.2691, -27.2691, -27.2691,  ..., -27.2691, -27.2691, -27.2691],
          [-27.2691, -27.2691, -27.2691,  ..., -27.2691, -27.2691, -27.2691],
          [-27.2691, -27.2691, -27.2691,  ..., -27.2691, -27.2691, -27.2691]],

         [[-27.2691, -27.2691,