# NumPy 基础练习

请你尝试使用学到的 NumPy 编程知识，解决如下问题。

In [1]:
import numpy as np

## 1. 文件读取，数组拼接，索引，类型转换，数组运算，数组创建，转置

(1) 现有一个图像数据集，存放在 `images_0.npy` 和 `images_1.npy` 中。请你先分别读取图像数据，然后沿第 0 轴（batch 轴）将两组数据进行拼接，赋值给 `images` 变量，并打印 `images` 的数据类型和形状，以及像素取值的最大值和最小值。

In [1]:
import numpy as np
images_0= np.load('images_0.npy')
images_1= np.load('images_1.npy')
images=np.concatenate([images_0, images_1], axis=0)
print('元素数据类型：', images.dtype)
print('形状：', images.shape)
print(np.min(images))
print(np.max(images))

元素数据类型： uint8
形状： (6, 16, 16, 3)
0
255


(2) 现在想要将 `images` 中的图像的尺寸（高度和宽度）减小一半。请你采用选取原图像中的偶数行和奇数列的方法缩减图像的尺寸。

In [32]:
import numpy as np
images_0= np.load('images_0.npy')
images_1= np.load('images_1.npy')
images=np.concatenate([images_0, images_1], axis=0)
images_2=np.delete(images, [range(0,16,2)], axis=2)
images_3=np.delete(images_2,[range(1,17,2)],axis=1)
print(images_3)
print('形状：', images_3.shape)

[[[[150  28 174]
   [ 18  25  73]
   [ 84 150 237]
   ...
   [140  76 239]
   [169 247  42]
   [109   2 115]]

  [[ 55 140 193]
   [ 67 155 150]
   [ 85  52 107]
   ...
   [102 182 175]
   [  9 228  83]
   [232  45 167]]

  [[ 15  81 187]
   [ 77 216 227]
   [ 83 117 184]
   ...
   [ 50 217   7]
   [246  34   2]
   [113 129  19]]

  ...

  [[147  42  16]
   [  2 173  88]
   [146   0  92]
   ...
   [197 232 245]
   [ 54 202 113]
   [ 99  60  27]]

  [[116 159  31]
   [193  58 252]
   [ 86 118 210]
   ...
   [ 71  58 112]
   [156 206   5]
   [214  67  69]]

  [[251 242 221]
   [207 118  22]
   [143 158 139]
   ...
   [105   5 153]
   [ 82  62 107]
   [194  61  44]]]


 [[[127 230  47]
   [ 58 244   1]
   [ 65  73 229]
   ...
   [161 213 140]
   [ 45  69 103]
   [100  31 120]]

  [[  2 226 122]
   [ 23  28 148]
   [ 49  12 219]
   ...
   [ 75 114  58]
   [183 126 240]
   [114  43  84]]

  [[250 232 153]
   [ 60 116  76]
   [193 254  37]
   ...
   [109  42  23]
   [127 246  33]
   [  3 154

(3) 当前，图片像素的取值为 0\~255。现在需要你对像素取值进行正规化，即将 0\~255 映射到 -1\~1。请注意类型转换！

In [34]:
x = np.array(images_3, dtype=np.float32)
y=x/255*2-1
print(y)

[[[[ 0.17647064 -0.78039217  0.36470592]
   [-0.85882354 -0.8039216  -0.42745095]
   [-0.34117645  0.17647064  0.85882354]
   ...
   [ 0.09803927 -0.40392154  0.8745098 ]
   [ 0.32549024  0.9372549  -0.67058825]
   [-0.14509803 -0.9843137  -0.09803921]]

  [[-0.5686275   0.09803927  0.5137255 ]
   [-0.47450978  0.21568632  0.17647064]
   [-0.3333333  -0.5921569  -0.1607843 ]
   ...
   [-0.19999999  0.427451    0.37254906]
   [-0.92941177  0.7882353  -0.3490196 ]
   [ 0.81960785 -0.64705884  0.30980396]]

  [[-0.88235295 -0.36470586  0.4666667 ]
   [-0.3960784   0.69411767  0.78039217]
   [-0.3490196  -0.08235294  0.4431373 ]
   ...
   [-0.60784316  0.7019608  -0.94509804]
   [ 0.92941177 -0.73333335 -0.9843137 ]
   [-0.11372548  0.01176476 -0.8509804 ]]

  ...

  [[ 0.15294123 -0.67058825 -0.8745098 ]
   [-0.9843137   0.35686278 -0.3098039 ]
   [ 0.14509809 -1.         -0.27843136]
   ...
   [ 0.54509807  0.81960785  0.92156863]
   [-0.5764706   0.58431375 -0.11372548]
   [-0.2235294  

(4) 现在，请你为图像的每一个像素分别加上在 $[-0.01, 0.01]$ 上均匀分布的噪声，但要求加入噪声后，像素取值仍要在 $[-1, 1]$ （超出部分需要截断）。

In [2]:
import random
number = random.uniform(-0.01,0.01)
z=y+number
[rows, cols,ROWS,COLS] = z.shape
for i in range(rows):
    for j in range(cols):
        for k in range(ROWS):
            for m in range(COLS):
                if(z[i,j,k,m]>=1):z[i,j,k,m]=1
print(z)


NameError: name 'y' is not defined

(5) 请将图像中取值在 $[-0.1, 0.1]$ 的像素赋值为 0。

In [37]:
for i in range(rows):
    for j in range(cols):
        for k in range(ROWS):
            for m in range(COLS):
                if(-0.1<=z[i,j,k,m]<=0.1):z[i,j,k,m]=0
print(z)

[[[[ 0.17551802 -0.7813448   0.3637533 ]
   [-0.85977614 -0.8048742  -0.4284036 ]
   [-0.34212908  0.17551802  0.85787094]
   ...
   [ 0.         -0.40487418  0.8735572 ]
   [ 0.3245376   0.9363023  -0.67154086]
   [-0.14605065 -0.9852663   0.        ]]

  [[-0.5695801   0.          0.5127729 ]
   [-0.4754624   0.2147337   0.17551802]
   [-0.33428594 -0.5931095  -0.16173692]
   ...
   [-0.2009526   0.42649838  0.37159643]
   [-0.9303644   0.7872827  -0.34997222]
   [ 0.81865525 -0.64801145  0.30885133]]

  [[-0.88330555 -0.3656585   0.46571407]
   [-0.39703104  0.69316506  0.77943957]
   [-0.34997222  0.          0.44218466]
   ...
   [-0.60879576  0.7010082  -0.94605064]
   [ 0.92845917 -0.73428595 -0.9852663 ]
   [-0.1146781   0.         -0.851933  ]]

  ...

  [[ 0.15198861 -0.67154086 -0.8754624 ]
   [-0.9852663   0.35591015 -0.31075653]
   [ 0.14414547 -1.0009526  -0.279384  ]
   ...
   [ 0.54414546  0.81865525  0.92061603]
   [-0.5774232   0.58336115 -0.1146781 ]
   [-0.22448201 

(6) 在 NumPy 中，图像数组的形状通常是 (batch, height, width, channel)，但在 PyTorch 中，图像张量的形状通常是 (batch, channel, height, width)。请你将当前图像数组按照 PyTorch 定义的维度顺序进行转换。

In [38]:
z.swapaxes(1,2)
z.swapaxes(1,3)
print(z)

[[[[ 0.17551802 -0.7813448   0.3637533 ]
   [-0.85977614 -0.8048742  -0.4284036 ]
   [-0.34212908  0.17551802  0.85787094]
   ...
   [ 0.         -0.40487418  0.8735572 ]
   [ 0.3245376   0.9363023  -0.67154086]
   [-0.14605065 -0.9852663   0.        ]]

  [[-0.5695801   0.          0.5127729 ]
   [-0.4754624   0.2147337   0.17551802]
   [-0.33428594 -0.5931095  -0.16173692]
   ...
   [-0.2009526   0.42649838  0.37159643]
   [-0.9303644   0.7872827  -0.34997222]
   [ 0.81865525 -0.64801145  0.30885133]]

  [[-0.88330555 -0.3656585   0.46571407]
   [-0.39703104  0.69316506  0.77943957]
   [-0.34997222  0.          0.44218466]
   ...
   [-0.60879576  0.7010082  -0.94605064]
   [ 0.92845917 -0.73428595 -0.9852663 ]
   [-0.1146781   0.         -0.851933  ]]

  ...

  [[ 0.15198861 -0.67154086 -0.8754624 ]
   [-0.9852663   0.35591015 -0.31075653]
   [ 0.14414547 -1.0009526  -0.279384  ]
   ...
   [ 0.54414546  0.81865525  0.92061603]
   [-0.5774232   0.58336115 -0.1146781 ]
   [-0.22448201 

## 2. 矩阵、向量运算，数学函数

已知旋转矩阵的定义为：

$$
\mathbf M(\theta )={\begin{bmatrix}\cos {\theta }&-\sin {\theta }\\ \sin {\theta }&\cos {\theta }\end{bmatrix}}
$$

向量 $\boldsymbol x$ 经旋转矩阵 $\mathbf M$ 作用后的向量为 $\mathbf M \boldsymbol x$。

(1) 请你生成一个旋转角度 $\theta = 30 \degree$ 的旋转矩阵。

In [51]:
import numpy as np
import math 
M=np.array([[math.cos(math.pi/6),-math.sin(math.pi/6)],[math.sin(math.pi/6),math.cos(math.pi/6)]])

(2) 现有向量 $\boldsymbol x = (1, 2)$。请计算经上一步旋转矩阵作用后的向量，以及旋转前后向量的模长。

In [53]:
x=np.array([1,2])
z=x@M
print(z)

[1.8660254  1.23205081]
